export const ADD_QUESTION = 'ADD_QUESTION';
export const CHANGE_QUESTION = "CHANGE_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const DELETE_ALL_QUESTIONS = "DELETE_ALL_QUESTIONS";
